### ISSUE TITLE
Error on attempt to use the graph

### ISSUE THREAD

**Issue by vovak** [bochkarevko/TCG#1]
> (base) vladimir.kovalenko@Vladimirs-MacBook-Pro-3 TCG % python main.py -n 10 --verbose
> INFO:root:Getting top 10 contributors
> INFO:root:Getting all files changed by top 10 contributors
> xargs: illegal option -- d
> usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements]] [-J replstr]
>              [-L number] [-n number [-x]] [-P maxprocs] [-s size]
>              [utility [argument ...]]
> INFO:root:Preparing graph
> comm: illegal option -- -
> usage: comm [-123i] file1 file2
> Traceback (most recent call last):
>   File "main.py", line 73, in <module>
>     plot_graph(contributors_list)
>   File "main.py", line 38, in plot_graph
>     count = int(shared_changed.stdout.decode('utf-8').split()[2])
> IndexError: list index out of range

This might have to do with variation in syntax of basic utilities between different OSs.
Could you please add a sample of extracted data to the repo?

**Comment by bochkarevko** [comment]
I have added data for the top 10/30/50 contributors to the React repo and added `--dry` option to the python script to skip the data retrieval part.

Sorry for inconvenience, I'll try to fix this asap.

**Comment by vovak** [comment]
Thank you for swift reaction. The `--dry` option didn't quite work for me.

> (base) vladimir.kovalenko@Vladimirs-MacBook-Pro-3 TCG % python3 main.py --dry -n 10
> comm: illegal option -- -
> usage: comm [-123i] file1 file2
> Traceback (most recent call last):
>   File "main.py", line 78, in <module>
>     plot_graph(contributors_list)
>   File "main.py", line 39, in plot_graph
>     count = int(shared_changed.stdout.decode('utf-8').split()[2])
> IndexError: list index out of range

**Comment by bochkarevko** [comment]
Sorry again, that's another utility problem, [MacOS' comm](https://ss64.com/osx/comm.html) does not have a `--total` option, working on a quick fix.

I was told at my Unix class that it's important to check if options are POSIX complaint, but I did not expect to encounter such problems so soon.

**Comment by bochkarevko** [comment]
The problem with `comm` should be fixed, now it outputs all shared filenames to `wc -l` that counts them, which is a bit messier, but should do the job.

**Comment by vovak** [comment]
Thanks.

Looks like it's not my day today though.

> (base) vladimir.kovalenko@Vladimirs-MacBook-Pro-3 TCG % python3 main.py --dry -n 10
> Traceback (most recent call last):
>   File "/Users/vladimir.kovalenko/opt/miniconda3/lib/python3.7/site-packages/graphviz/backend.py", line 164, in run
>     proc = subprocess.Popen(cmd, startupinfo=get_startupinfo(), **kwargs)
>   File "/Users/vladimir.kovalenko/opt/miniconda3/lib/python3.7/subprocess.py", line 775, in __init__
>     restore_signals, start_new_session)
>   File "/Users/vladimir.kovalenko/opt/miniconda3/lib/python3.7/subprocess.py", line 1522, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'neato': 'neato'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "main.py", line 80, in <module>
>     plot_graph(contributors_list)
>   File "main.py", line 60, in plot_graph
>     g.view()
>   File "/Users/vladimir.kovalenko/opt/miniconda3/lib/python3.7/site-packages/graphviz/files.py", line 246, in view
>     quiet=quiet, quiet_view=quiet_view)
>   File "/Users/vladimir.kovalenko/opt/miniconda3/lib/python3.7/site-packages/graphviz/files.py", line 209, in render
>     quiet=quiet)
>   File "/Users/vladimir.kovalenko/opt/miniconda3/lib/python3.7/site-packages/graphviz/backend.py", line 221, in render
>     run(cmd, capture_output=True, cwd=cwd, check=True, quiet=quiet)
>   File "/Users/vladimir.kovalenko/opt/miniconda3/lib/python3.7/site-packages/graphviz/backend.py", line 167, in run
>     raise ExecutableNotFound(cmd)
> graphviz.backend.ExecutableNotFound: failed to execute ['neato', '-Tpdf', '-O', 'graph_10.gv'], make sure the Graphviz executables are on your systems' PATH
> (base) vladimir.kovalenko@Vladimirs-MacBook-Pro-3 TCG % pip install graphviz
> Requirement already satisfied: graphviz in /Users/vladimir.kovalenko/opt/miniconda3/lib/python3.7/site-packages (0.14.2)
> (base) vladimir.kovalenko@Vladimirs-MacBook-Pro-3 TCG %

**Comment by bochkarevko** [comment]
I changed the `-d` option in the `xargs` call to `-0` with the help from `tr`, so the data retrieval step should work on MacOS now.

**Comment by bochkarevko** [comment]
Can you try switching the engine string at line 31 in `main.py` to `sfdp`? It's the deafult engine, the graph will look even worse than it does with `neato`, but at least it should work (as is implied by 'default').

**Comment by vovak** [comment]
Already trying `brew install graphvis`

**Comment by vovak** [comment]
tada
![image](https://user-images.githubusercontent.com/1163206/95366106-45f8ff80-08d3-11eb-9dd8-c67724f1b5d7.png)

=
